# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- build-projet
- playwright-testCanEleve
- playwright-test
- playwright-testLycee
- playwright-pdf
- playwright-pdfDNB
- playwright-pdfBAC

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml


default:
  image: node:18.16.0
  cache:
    key:
      files:
      - pnpm-lock.yaml
    paths:
      - .pnpm-store

.install_dependencies:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - NODE_OPTIONS=--max-old-space-size=4096 pnpm install
    - nohup pnpm start &
    - sleep 20
    - until $(curl --output /dev/null --head --fail http://localhost:80/alea/); do printf '.'; sleep 10; done
    - sleep 60

.install_dependenciesPDF:
  before_script:
    - pnpm config set store-dir .pnpm-store
    - pnpm -v
    - lualatex -v
    - pnpm exec playwright install --with-deps chromium
    - ls /root/.cache/ms-playwright/
    - pnpm add playwright@1.44.1 --save-dev
    - pnpm install
    - nohup pnpm start &
    - sleep 10
    - until $(curl --output /dev/null --head --fail http://localhost:80/alea/); do printf '.'; sleep 10; done
    - sleep 30
  
.install_dependenciesPDFDNB:
  before_script:
    - pnpm config set store-dir .pnpm-store
    - pnpm -v
    - lualatex -v
    - pnpm exec playwright install --with-deps chromium
    - ls /root/.cache/ms-playwright/
    - pnpm add playwright@1.44.1 --save-dev
    - git clone https://forge.apps.education.fr/coopmaths/dnb.git ./public/static/dnb
    - pnpm install
    - nohup pnpm start &
    - sleep 10
    - until $(curl --output /dev/null --head --fail http://localhost:80/alea/); do printf '.'; sleep 10; done
    - sleep 30

.install_dependenciesPDFBAC:
  before_script:
    - pnpm config set store-dir .pnpm-store
    - pnpm -v
    - lualatex -v
    - pnpm exec playwright install --with-deps chromium
    - ls /root/.cache/ms-playwright/
    - pnpm add playwright@1.44.1 --save-dev
    - git clone https://forge.apps.education.fr/coopmaths/bac.git ./public/static/bac
    - pnpm install
    - nohup pnpm start &
    - sleep 10
    - until $(curl --output /dev/null --head --fail http://localhost:80/alea/); do printf '.'; sleep 10; done
    - sleep 30

.testCIPDF:
  image: guironne/tex-live-nodejs-playwright8
  extends: .install_dependenciesPDF
  stage: playwright-pdf
  allow_failure: true
  rules:
  - if: $CI_COMMIT_BRANCH == "guironne-jobs"
    when: manual
  - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_TEST_MA == "PDF"
    when: always
  - when: never
  retry:
    max: 2
    when: 
    - runner_system_failure
    - script_failure
    - unknown_failure
  artifacts:
    when: always
    paths:
      - tests/e2e/logs
      - updatefile
    exclude:
      - updatefile/output/*.*
    expire_in: 20 day

.testCI:
  extends: .install_dependencies
  image: mcr.microsoft.com/playwright:v1.45.1-jammy
  stage: playwright-test
  allow_failure: true
  rules:
  - if: $CI_COMMIT_BRANCH == "main" && $CI_OPEN_MERGE_REQUESTS
    when: never
  - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"
    when: always
  - if: $CI_COMMIT_BRANCH == "guironne-jobs"
    when: manual
  - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_TEST_MA == "CONSOLE"
    when: always
  - when: never
  retry:
    max: 2
    when: 
    - runner_system_failure
    - script_failure
    - unknown_failure
  artifacts:
    when: always
    paths:
      - tests/e2e/logs
    expire_in: 10 day

test6e:
  extends: .testCI
  script:
    - NIV=6e/6 pnpm test:e2e:console_errors

test5e:
  extends: .testCI
  script:
    - NIV=5e/5 pnpm test:e2e:console_errors

test4e:
  extends: .testCI
  script:
    - NIV=4e/4 pnpm test:e2e:console_errors

test3e:
  extends: .testCI
  script:
    - NIV=3e/3 pnpm test:e2e:console_errors

test2e:
  extends: .testCI
  stage: playwright-testLycee
  script:
    - NIV=2e/2 pnpm test:e2e:console_errors

test1e:
  extends: .testCI
  stage: playwright-testLycee
  script:
    - NIV=1e/1 pnpm test:e2e:console_errors

testQCM:
  extends: .testCI
  script:
    - NIV=QCM pnpm test:e2e:console_errors

testCan6e5e4e3e:
  extends: .testCI
  script:
    - NIV=can/6e^can/5e^can/4e^can/3e pnpm test:e2e:console_errors

testCan2e1e:
  extends: .testCI
  script:
    - NIV=can/2e^can/1e pnpm test:e2e:console_errors

testCan2e1ePDF:
  extends: .testCIPDF
  script:
    - NIV=can/2e^can/1e pnpm test:e2e:pdfexports

testCan6e5e4e3ePDF:
  extends: .testCIPDF
  script:
    - NIV=can/6e^can/5e^can/4e^can/3e pnpm test:e2e:pdfexports
    - pnpm -v

testBAC20202024PDF:
  extends: 
    - .testCIPDF
    - .install_dependenciesPDFBAC
  stage: playwright-pdfBAC
  script:
    - NIV=bac_2023^bac_2022^bac_2021 pnpm test:e2e:pdfexports

testDNB20132015PDF:
  extends: 
    - .testCIPDF
    - .install_dependenciesPDFDNB
  stage: playwright-pdfDNB
  script:
    - NIV=dnb_2013^dnb_2014^dnb_2015 pnpm test:e2e:pdfexports

testDNB20162019PDF:
  extends: 
    - .testCIPDF
    - .install_dependenciesPDFDNB
  stage: playwright-pdfDNB
  script:
    - NIV=dnb_2016^dnb_2017^dnb_2018^dnb_2019 pnpm test:e2e:pdfexports

testDNB20202024PDF:
  extends: 
    - .testCIPDF
    - .install_dependenciesPDFDNB
  stage: playwright-pdfDNB
  script:
    - NIV=dnb_2020^dnb_2021^dnb_2022^dnb_2023 pnpm test:e2e:pdfexports

test6ePDF:
  extends: .testCIPDF
  script:
    - NIV=6e/6 pnpm test:e2e:pdfexports
    - pnpm -v

test5ePDF:
  extends: .testCIPDF
  script:
    - NIV=5e/5 pnpm test:e2e:pdfexports
    - pnpm -v

test4ePDF:
  extends: .testCIPDF
  script:
    - NIV=4e/4 pnpm test:e2e:pdfexports
    - pnpm -v

test3ePDF:
  extends: .testCIPDF
  script:
    - NIV=3e/3 pnpm test:e2e:pdfexports
    - pnpm -v

bcommit:
  stage: build-projet
  script:
    - echo "CI_COMMIT_BRANCH '$CI_COMMIT_BRANCH'"
    - echo "CI_OPEN_MERGE_REQUESTS '$CI_OPEN_MERGE_REQUESTS'"
    - echo "CI_PIPELINE_SOURCE '$CI_PIPELINE_SOURCE'"
    - echo "$CI_COMMIT_AUTHOR"
  rules:
    - when: always
  artifacts:
    when: on_failure

build:
  extends: .testCI
  stage: build-projet
  script:
    - echo "CI_COMMIT_BRANCH '$CI_COMMIT_BRANCH'"
    - echo "CI_OPEN_MERGE_REQUESTS '$CI_OPEN_MERGE_REQUESTS'"
    - echo "CI_PIPELINE_SOURCE '$CI_PIPELINE_SOURCE'"
    - NODE_OPTIONS=--max-old-space-size=4096 pnpm build
    - echo "$CI_COMMIT_AUTHOR"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always
  artifacts:
    when: on_failure

playwright-testCanEleve:
  extends: .testCI
  stage: playwright-testCanEleve
  script:
    - pnpm test:e2e:views
  rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#       when: always
    - if: $CI_COMMIT_BRANCH == "main" && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "guironne-jobs"
      when: always
    - when: never
  artifacts:
    when: on_failure

playwright-testConsistency:
  extends: .testCI
  stage: playwright-testCanEleve
  script:
    - pnpm test:e2e:consistency
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "guironne-jobs"
      when: always
    - when: never
  artifacts:
    when: on_failure

playwright-testInteractivity:
  extends: .testCI
  stage: playwright-testCanEleve
  script:
    - pnpm test:e2e:interactivity
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "guironne-jobs"
      when: always
    - when: never
  artifacts:
    when: on_failure